version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      tanstack:
        patterns:
          - "@tanstack/*"
      drizzle:
        patterns:
          - "drizzle-*"
      octokit:
        patterns:
          - "@octokit/*"
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
