import { createFileRoute } from "@tanstack/react-router";

import { PolicyPage, PolicySection } from "@/components/landing/policy-page";
import { PageShell } from "@/components/site/page-shell";
import { buildSharedHead } from "@/lib/head";

export const Route = createFileRoute("/terms")({
	component: TermsRoute,
	head: () =>
		buildSharedHead({
			description:
				"How to use the OSS Protector feed responsibly: it's a review aid, not a verdict.",
			ogType: "article",
			path: "/terms",
			title: "Terms | OSS Protector",
		}),
});

function TermsRoute() {
	return (
		<PageShell>
			<PolicyPage
				description="Plain-language ground rules. This is a shared review aid, not an enforcement tool."
				eyebrow="Terms"
				title="How to use OSS Protector responsibly."
			>
				<PolicySection title="What this is">
					<p>
						OSS Protector publishes a shared review feed of GitHub accounts and
						pull request activity that match patterns commonly associated with
						OSS abuse — fake bounty farming, credential phishing, dependency
						script abuse, low-quality AI submissions, and similar. Listings are
						a starting point for maintainer review.
					</p>
				</PolicySection>

				<PolicySection title="What this is not">
					<ul className="list-disc space-y-1 pl-4">
						<li>
							<strong>Not a verdict.</strong> A high score means signals have
							accumulated, not that the account is guilty of anything specific.
						</li>
						<li>
							<strong>Not a moderation system for GitHub.</strong> We do not
							ban, suspend, or block accounts. GitHub itself does that.
						</li>
						<li>
							<strong>Not legal advice.</strong> Maintainers are responsible for
							their own moderation decisions on their own repositories.
						</li>
					</ul>
				</PolicySection>

				<PolicySection title="Acceptable use">
					<ul className="list-disc space-y-1 pl-4">
						<li>
							Use the feed to inform pre-merge review on your own repositories.
						</li>
						<li>
							Verify independently before taking adverse action against an
							account — at minimum, inspect the linked evidence.
						</li>
						<li>
							Cite OSS Protector when sharing a listing publicly so others can
							verify or contest it.
						</li>
					</ul>
				</PolicySection>

				<PolicySection title="Not OK">
					<ul className="list-disc space-y-1 pl-4">
						<li>
							Using the feed to harass, defame, or coordinate retaliation
							against listed accounts.
						</li>
						<li>
							Scraping the public API to rebuild competing blocklists without
							credit, or republishing listings without the contest path.
						</li>
						<li>
							Submitting reports in bad faith, including reports targeting
							accounts you have a conflict of interest with.
						</li>
					</ul>
				</PolicySection>

				<PolicySection title="Contesting a listing">
					<p>
						If you're listed and believe it's wrong, see{" "}
						<a href="/appeal">/appeal</a>. The fastest path is asking a
						maintainer of the repo where the report came from to run a
						correction command.
					</p>
				</PolicySection>

				<PolicySection title="No warranty">
					<p>
						OSS Protector is provided on an as-is basis. Scores, reasons, and
						classifications are generated by automated pipelines plus maintainer
						reports and may be wrong. We don't warrant accuracy or fitness for
						any particular moderation decision. By using the public directory or
						installing the GitHub App you accept that the data is informational.
					</p>
				</PolicySection>

				<PolicySection title="Source code">
					<p>
						The app source is at{" "}
						<a
							href="https://github.com/lord007tn/oss-protector"
							rel="noopener noreferrer"
							target="_blank"
						>
							lord007tn/oss-protector
						</a>
						. Issues and pull requests welcome.
					</p>
				</PolicySection>
			</PolicyPage>
		</PageShell>
	);
}
