/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProtectorsRouteImport } from './routes/protectors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsLoginRouteImport } from './routes/accounts_.$login'
import { Route as RepoOwnerNameRouteImport } from './routes/repo.$owner.$name'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectorsRoute = ProtectorsRouteImport.update({
  id: '/protectors',
  path: '/protectors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsLoginRoute = AccountsLoginRouteImport.update({
  id: '/accounts_/$login',
  path: '/accounts/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoOwnerNameRoute = RepoOwnerNameRouteImport.update({
  id: '/repo/$owner/$name',
  path: '/repo/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/docs': typeof DocsRoute
  '/appeal': typeof AppealRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/protectors': typeof ProtectorsRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/accounts/$login': typeof AccountsLoginRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/docs': typeof DocsRoute
  '/appeal': typeof AppealRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/protectors': typeof ProtectorsRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/accounts/$login': typeof AccountsLoginRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/docs': typeof DocsRoute
  '/appeal': typeof AppealRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/protectors': typeof ProtectorsRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/accounts_/$login': typeof AccountsLoginRoute
  '/repo/$owner/$name': typeof RepoOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/docs'
    | '/appeal'
    | '/dashboard'
    | '/feed'
    | '/install'
    | '/login'
    | '/methodology'
    | '/privacy'
    | '/protectors'
    | '/settings'
    | '/sponsors'
    | '/terms'
    | '/accounts/$login'
    | '/repo/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/docs'
    | '/appeal'
    | '/dashboard'
    | '/feed'
    | '/install'
    | '/login'
    | '/methodology'
    | '/privacy'
    | '/protectors'
    | '/settings'
    | '/sponsors'
    | '/terms'
    | '/accounts/$login'
    | '/repo/$owner/$name'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/docs'
    | '/appeal'
    | '/dashboard'
    | '/feed'
    | '/install'
    | '/login'
    | '/methodology'
    | '/privacy'
    | '/protectors'
    | '/settings'
    | '/sponsors'
    | '/terms'
    | '/accounts_/$login'
    | '/repo/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  DocsRoute: typeof DocsRoute
  AppealRoute: typeof AppealRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtectorsRoute: typeof ProtectorsRoute
  SettingsRoute: typeof SettingsRoute
  SponsorsRoute: typeof SponsorsRoute
  TermsRoute: typeof TermsRoute
  AccountsLoginRoute: typeof AccountsLoginRoute
  RepoOwnerNameRoute: typeof RepoOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protectors': {
      id: '/protectors'
      path: '/protectors'
      fullPath: '/protectors'
      preLoaderRoute: typeof ProtectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/$login': {
      id: '/accounts_/$login'
      path: '/accounts/$login'
      fullPath: '/accounts/$login'
      preLoaderRoute: typeof AccountsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$owner/$name': {
      id: '/repo/$owner/$name'
      path: '/repo/$owner/$name'
      fullPath: '/repo/$owner/$name'
      preLoaderRoute: typeof RepoOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  DocsRoute: DocsRoute,
  AppealRoute: AppealRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectorsRoute: ProtectorsRoute,
  SettingsRoute: SettingsRoute,
  SponsorsRoute: SponsorsRoute,
  TermsRoute: TermsRoute,
  AccountsLoginRoute: AccountsLoginRoute,
  RepoOwnerNameRoute: RepoOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
