/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProtectorsRouteImport } from './routes/protectors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InstallRouteImport } from './routes/install'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as ClankersRouteImport } from './routes/clankers'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClankersLoginRouteImport } from './routes/clankers.$login'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectorsRoute = ProtectorsRouteImport.update({
  id: '/protectors',
  path: '/protectors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankersRoute = ClankersRouteImport.update({
  id: '/clankers',
  path: '/clankers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankersLoginRoute = ClankersLoginRouteImport.update({
  id: '/$login',
  path: '/$login',
  getParentRoute: () => ClankersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/clankers': typeof ClankersRouteWithChildren
  '/contest': typeof ContestRoute
  '/install': typeof InstallRoute
  '/privacy': typeof PrivacyRoute
  '/protectors': typeof ProtectorsRoute
  '/terms': typeof TermsRoute
  '/clankers/$login': typeof ClankersLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/clankers': typeof ClankersRouteWithChildren
  '/contest': typeof ContestRoute
  '/install': typeof InstallRoute
  '/privacy': typeof PrivacyRoute
  '/protectors': typeof ProtectorsRoute
  '/terms': typeof TermsRoute
  '/clankers/$login': typeof ClankersLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/clankers': typeof ClankersRouteWithChildren
  '/contest': typeof ContestRoute
  '/install': typeof InstallRoute
  '/privacy': typeof PrivacyRoute
  '/protectors': typeof ProtectorsRoute
  '/terms': typeof TermsRoute
  '/clankers/$login': typeof ClankersLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/clankers'
    | '/contest'
    | '/install'
    | '/privacy'
    | '/protectors'
    | '/terms'
    | '/clankers/$login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/clankers'
    | '/contest'
    | '/install'
    | '/privacy'
    | '/protectors'
    | '/terms'
    | '/clankers/$login'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/clankers'
    | '/contest'
    | '/install'
    | '/privacy'
    | '/protectors'
    | '/terms'
    | '/clankers/$login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ClankersRoute: typeof ClankersRouteWithChildren
  ContestRoute: typeof ContestRoute
  InstallRoute: typeof InstallRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtectorsRoute: typeof ProtectorsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protectors': {
      id: '/protectors'
      path: '/protectors'
      fullPath: '/protectors'
      preLoaderRoute: typeof ProtectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clankers': {
      id: '/clankers'
      path: '/clankers'
      fullPath: '/clankers'
      preLoaderRoute: typeof ClankersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clankers/$login': {
      id: '/clankers/$login'
      path: '/$login'
      fullPath: '/clankers/$login'
      preLoaderRoute: typeof ClankersLoginRouteImport
      parentRoute: typeof ClankersRoute
    }
  }
}

interface ClankersRouteChildren {
  ClankersLoginRoute: typeof ClankersLoginRoute
}

const ClankersRouteChildren: ClankersRouteChildren = {
  ClankersLoginRoute: ClankersLoginRoute,
}

const ClankersRouteWithChildren = ClankersRoute._addFileChildren(
  ClankersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  ClankersRoute: ClankersRouteWithChildren,
  ContestRoute: ContestRoute,
  InstallRoute: InstallRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectorsRoute: ProtectorsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
